### ISSUE TITLE
Deis Output as separate plugin

### ISSUE THREAD

**Issue by sstarcher** [deis/fluentd#52]
The repo would be cleaner if the Deis Output Plugin was split into it's own repo as a separate fluentd gem

**Comment by jchauncey** [comment]
We didnt do that because it means having to deal with publishing it to ruby
gems and things like that. We run the deis output tests as part of ci and
you would only ever run this plugin with our fluentd image. Just didnt seem
like the juice was worth the squeeze to make it a separate repo.

**Comment by mboersma** [comment]
> you would only ever run this plugin with our fluentd image

It might be cleaner but as @jchauncey pointed out, it's not really generalizable outside Deis Workflow, so it's hard to justify the effort to publish a proper gem. If someone were to contribute such a change it could be welcome, but it probably won't happen otherwise.

Since it's not on the current radar, I'm going to close this request. But please re-open it if you think it's worth keeping the idea alive, or if someone is actually planning to implement it. 😄
